#!/bin/bash

#
# This is a temporary script to automate the building and running process of the operating system, if you wish to manually do it, you must:
# 'make all' and then run 'qemu-system-i386' with the disk image as an argument.
# It SHOULD handle most of the edge-cases related to error-handling; however, if you encounter any unknown error, you can refer to that tool's official docs.
#
# It's a replacement to what in the future (I hope near!) might be a GUI version to build the operating system.
#
# Last modified: 10/04/2025
#

DISK_IMG=jaos.img

MEDIA=build/$DISK_IMG	# Bootable image
ARCH=i386				# Architecture
RAM=128				# MBs

CPU=core2duo

# Checks a given string, returns 1 if the string is 'y', 0 otherwise
input_yes() {
	read prompt
	if [[ $( echo $prompt | tr '[:upper:]' '[:lower:]' ) == 'y' ]]; then
		true
	else
		false
	fi
}

# Exits if the bootable image is not found.
if [ ! -f $MEDIA ]; then
     echo "Bootable file - '$MEDIA' - not found locally."
     exit
fi

# Prompts QEMU installation if not installed
if ! command -v qemu-system-x86_64 &> /dev/null || ! command -v qemu-system-i386 &> /dev/null; then
	echo "Error: qemu-system-i386 or qemu-system-x86_64 packages not installed, do you want to install it to continue? [y/n]"
	input_yes
	status=$?
	if [ "$status" -eq 0 ]; then
          sudo apt install qemu-system-x86
          sudo apt install qemu-system-common
		echo "Finished installing the packages, running the makefile..."
     else
		echo "Can't continue properly executing without qemu, exiting..."
          exit
     fi
fi

# Prompts MAKE installation if not installed
if ! command -v make &> /dev/null; then
	echo "Error: make package not installed, do you want to install it to continue? [y/N]"
	input_yes
	status=$?
	if [ "$status" -eq 0 ]; then
		sudo apt install make
	else
		echo "Can't continue properly executing without make, exiting..."
		exit
	fi
fi

# Build the image
make clean
make

# Run arguments
qemu-system-$ARCH \
-cpu $CPU \
-m $RAM \
-fda $MEDIA \

#-usb \
#-vga std \
